apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-ingestor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-ingestor-role
subjects:
  - kind: ServiceAccount
    name: log-ingestor-sa