apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-ingestor-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-ingestor-role
subjects:
  - kind: ServiceAccount
    name: log-ingestor-sa
    namespace: default